### ISSUE TITLE
Global parameter disappears while updating tags in  data factory

### ISSUE THREAD

**Issue by pbakhil** [Azure/Azure-DataFactory#214]
We have  very strange issue, global parameter is used in our azure data factory(ADF) pipeline. The  ADF is created through ARM template, the ADF with global parameters get created properly when the ARM template is executed. The strange issue we noticed was when we add tags to the ADF the global parameters get disappeared and which makes the pipelines to fail.

**Comment by fhljys** [comment]
Fixed

**Comment by shweyde** [comment]
Is this issue fixed. I am facing similar issue

**Comment by jmcallister-msft** [comment]
@shweyde how are you deploying updates to your factory tags and global parameters? The root cause of this issue has been resolved, but there are some scenarios where tags are removed by design, such as deploying a template with "Include in ARM Template" selected. More info here: https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters#cicd
