### ISSUE TITLE
ADF Extension in Storage Explorer - RBAC issue 

### ISSUE THREAD

**Issue by SudhirNune** [Azure/Azure-DataFactory#256]
We don't see any thing mentioned in Documentation about RBAC, by exposing the ADF LS to everyone, even a person with LS (Read access) can now use the Target LS and delete or add files from production, which should not be an expected.

Can you please shred some light on who this issue addressed ?

ADF Extension to Storage Explorer: [https://github.com/Azure/Azure-DataFactory/tree/main/StorageExplorerExtension](url)

**Comment by fhljys** [comment]
@SudhirNune, if a person only have LS read permission, how can he delete or add files? The LS in the factory is encrypted. Only ADF can decrypt that credential. Do delete or add files, you mean create another pipeline with delete/copy activity? But the user only have read permission, he won't be able to run the pipeline. Please share more details about your concern. Thanks.

**Comment by SudhirNune** [comment]
Hi @fhljys ,

Can you please help me understand the Authentication Mechanism of the ADF Extension and what is the RBAC considered as per below scenario - Here Me as  User

1. User Has only view access to a Storage Account
2. ADF has LS - PROD on the Storage Account with Full Access
3. User Add ADF Extension to Storage Explorer
4. When he opens up the LS - PROD, what actions he can perform ?
a. View
b. download
c. upload

**Comment by fhljys** [comment]
You mean in storage explorer, he select the factory, and then select that LS mentioned in your No. 2, then what he can do, right? 

ADF extension will only use that LS to list files/folder in the ADF panel, and then user can choose to copy a file or folder to another destination. 
So basically, he can only view the file/folder list, and can't download or upload. He can't view the file or file content with the ADF extension.

This extension is mainly targeting users who want to copy files easily.

**Comment by fhljys** [comment]
@SudhirNune , let me know if the above explanation works. If yes, I'd like to close this issue :)

**Comment by SudhirNune** [comment]
@fhljys, 2 things I observe, the Extension is creating a new Pipeline, Datasets & LS (if a new storage account is accessed) & this is even publishing the Pipelines.

In our ENV we have ADF is Git Enabled, so the Publish happened directly I can not delete / clean as the Publish will not work upon Deletion and over time we are going to have a lot of these junk Pipelines created.

I need to test the ADF RBAC behaviour more, if my ADF Just has me reader role when will the Pipeline Still be created ?? Have you tested the Various Role behaviors ?

**Comment by fhljys** [comment]
HI @SudhirNune , regarding git enabled factory, you have a good point. We will consider to disable selecting these factories and make it clear in document. We'd suggest you use another factory for this extension and the extension can actually help you create one if you have correct permission. 
After copy, we show a "clean resource" button next to the copy status. With that button, you could clean all the resources we created. But it is not available once you closed that panel. So you have to go to ADF UI to manage the resources. And ADF UI doesn't allow publish in live mode once git is enabled so that customers doesn't mess the resources in git and live. 
For now, if you already created such resources with ADF extension, you can consider use powershell to remove it. In future, we don't suggest customers use git enabled factory with ADF extension. 

Regarding RBAC, you don't need to worry about it. We are still calling ADF API with your user token. Permission is controlled well by ADF API (Otherwise, it would be a security hole:) ) If you only have reader role, I don't think even you can go to the second page of the ADF extension. Because we will do test connection before you go to next page. Reader role doesn't have permission to do test connection. It will fail once you click "continue" button.

**Comment by fhljys** [comment]
Btw, @SudhirNune, I am also interested in your scenarios. Why do you consider this extension? If you are using git already, you are actually an advanced user of ADF. :) . This extension is mainly targeting people who are not familiar with ADF and provide them a very easy-to-use drag & drop experience. So this extension only has very limited functionality. For other rich features, ADF UI will always be the recommended tool.

**Comment by SudhirNune** [comment]
@fhljys  - We use storage explorer, and I saw the extension pop-up and installed and started exploring the features and trying to understand the use cases, so that we can push to our users.

**Comment by fhljys** [comment]
@SudhirNune , we released a new version which disabled git associated factories. For those factories, we don't recommend this extension. 
For the other RBAK issue you mentioned, it is not an issue based on my previous statement. 
Hence close this issue. 

Thanks for interesting in this extension. And feel free contact us if you need any help or you have any suggestions.
