### ISSUE TITLE
Using azure-data-factory-utilities to produce ARM template produce invalid file.

### ISSUE THREAD

**Issue by rihanmeij-haefele** [Azure/Azure-DataFactory#285]
I am using @microsoft/azure-data-factory-utilities in my CI/CD pipeline to produce the ARM template as described [here ](https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment-improvements)

If I compare ARMTemplateForFactory.json that is produced by this process is different to the file that is produced from the publishing from inside the data factory.  This missing element is what I believe is breaking the release of the ARM template to my resources.  

I have committed all the lines that are the same
**The file produced by the data factory publish:**
Parameter section
`{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"factoryName": {
			"type": "string",
			"metadata": "Data Factory name",
			"defaultValue": "data factory name"
		},
		"dataFactory_location": {
			"type": "string",
			"defaultValue": "uksouth"
		}
`
Resource section
`
{
			"name": "[parameters('factoryName')]",
			"type": "Microsoft.DataFactory/factories",
			"apiVersion": "2018-06-01",
			"properties": {},
			"dependsOn": [],
			"location": "[parameters('dataFactory_location')]"
		}
`
**The file produced by using the data factory utility**
Parameter section
  The location parameter is missing
Resource section
`
{
            "name": "[parameters('factoryName')]",
            "type": "Microsoft.DataFactory/factories",
            "apiVersion": "2018-06-01",
            "properties": {},
            "dependsOn": []
        }
`

According to the [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/2018-06-01/factories?tabs=json), location is not required, however when I try to release that template is fails:
`
The location property is required for this definition.
`

I was expecting the data factory utility to produce an arm template that produces the same results as the publish inside the data factory UI.

**Comment by jmcallister-msft** [comment]
Hi @rihanmeij-haefele, sorry to hear you are running into this issue. Given you are doing CI/CD but do not appear to have any global parameters for this factory, as a workaround you could unselect "Include in ARM template" in the ADF UX so that the ARM template does not have the factory resource included. This will prevent the error above as the resource missing the location property will not be generated at all. If you do need global parameters, you could also deploy with PowerShell to avoid including the factory ARM template; this is actually the recommended approach for customers using the new flow. https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters#cicd

The above steps should unblock you from using automated publish, but I also tried reproducing this issue. When I generate the template I do see the location parameterized on the factory resource. Could you provide more details on your factory configuration or ideally create a support case so we can reproduce the issue with your support files?

**Comment by jmcallister-msft** [comment]
@rihanmeij-haefele Two other possibilities:
- Can you check in your git repo that you have a file named `<factory-name>.json` in the `factory` folder? 
- Is it possible that you have spelled the factory name wrong or not included it in the FactoryId parameter? Ex. `C:\DataFactories\DevDataFactory /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testResourceGroup/providers/Microsoft.DataFactory/factories/**DevDataFactory** ArmTemplateOutput`

**Comment by rihanmeij-haefele** [comment]
Thank you that resolved the problem.

What the problem was and the fix for it:

We created the DataFactory resources in the resource group via TerraForm.  When we created code integration of data factory, the check box called "Include in ARM template" (it is under Manage/Global parameters) was selected that added into the ARM template the resources to create the data factory.  Because we have already created DataFactory via TerraForm this was not necessary. Excluding the data factory in the arm template fix the problem.

We now have a much improved SDLC and a beautiful release pipeline, thank you @jmcallister-msft
