### ISSUE TITLE
Please provide well formatted steps about how to use spark on DataFactory

### ISSUE THREAD

**Issue by chhantyal** [Azure/Azure-DataFactory#38]
Hi,
I am looking to use Spark with DataFactory. While Hive, Pig etc are well documented, but unfortunately not Spark.

All I could find on the internet was this sample https://github.com/Azure/Azure-DataFactory/tree/master/Samples/Spark even then, read me is not well formatted. Thus very hard to read and understand.

I would really appreciate if you could add more detailed docs about using Spark with DataFactory.

Thank you

**Comment by karma0** [comment]
+1

[This article](https://docs.microsoft.com/en-us/azure/data-factory/data-factory-spark) seems to detail this sample, but doesn't give enough information either.  Where do I place the file(s) for ingestion, and where do I get said files?

Following the article, I'm able to create a full DF + Spark deployment, but it fails.  Possibly because there's no inputs assigned.

**Comment by chhantyal** [comment]
I could not make HDInsights on demand following these examples.

So I wrote automation scripts to bring HDInsights cluster up and submit spark jobs using Data Factory. Not really optimal, but seems to work.

**Comment by gauravmalhot** [comment]
The documentation for spark activity in ADF is here:
https://docs.microsoft.com/en-us/azure/data-factory/data-factory-spark

**Comment by chhantyal** [comment]
HDInsight on Demand is not supported for Spark:

> Spark Activity supports only existing (your own) HDInsight Spark cluster. It does not support an on-demand HDInsight linked service.
