### ISSUE TITLE
Cannot update packages of ADFCustomActivityRunner

### ISSUE THREAD

**Issue by RobertoPrevato** [Azure/Azure-DataFactory#42]
Hi,
Packages in ADFCustomActivityRunner cannot be updated, failing with error message:

> Failed to add reference. The package 'Microsoft.Azure.Common' tried to add a framework reference to 'System.Threading' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by daosul** [comment]
Hi Roberto,
Can you update the ADFCustomActivityRunner on its own instead of updating all packages together? The package has a dependency on Microsoft.Azure.Common and for some reason its latest version is causing the problem. I will investigate it but just updating ADFCustomActivityRunner on its own should solve your issue. 
Dan

**Comment by RobertoPrevato** [comment]
Hi Dan,
Thanks for your answer, and sorry for taking so long to give you a feedback. Updating the ADFCustomActivityRunner was fine.
Thanks,
Roberto
