### ISSUE TITLE
Integration Runtime Upgrade Breaks Sink Connections

### ISSUE THREAD

**Issue by daharmon** [Azure/Azure-DataFactory#472]
Our integration runtime version was updated to 5.22.8312.1 yesterday and it can no longer connect to local drives. I get an error "c cannot be resolved". I tried upgrading to 5.23 with no luck but if I downgrade to 5.21, everything works again. I have not turned off auto-update but that is not ideal. Any ideas?

**Comment by KeynesY** [comment]
Having the ability to read / write local files on selfhosted integration runtime (SHIR) exhibits a big security hole, so this feature should have been discontinued to avoid any potential security breach. It's highly recommended to move to the latest version of SHIR and move any data stores to a remote machine.

Let's think about this scenario. Pipeline author, who usually shouldn't have the access to SHIR, could easily preview system files in SHIR using File System connector without asking for the permission from IT admin who is accountable for SHIR. The author may even overwrite system files to run some malicious code, which can do even worse things, like sniffing network traffic, stealing password, etc. There're a lot of customers who use shared SHIR feature. It makes things even worse, as they bad guy may observe activities from other factories that s/he would not have permission to.

There're also a few other minor reasons why customers should not host data stores in SHIR machine. 1. performance impact; 2. not working well in scenario of SHIR HA (High Availability).

Hope this helps.

**Comment by daharmon** [comment]
Unfortunately, we have a legacy process that involves a MS Access database. The only way I could get datafactory to use MS access as a data source was to install the access driver on the SHIR VM and put the mdb file on the local file system. I've tried putting the file on an azure network share but I've had no luck getting data factory to connect to it. To make matters more confusing, one of the examples when creating a connection in ADF to a binary file, uses c:\, which makes it seem like it's supported. Do you have any better ways of connecting to an access database in ADF? Examples are very sparse.

**Comment by KeynesY** [comment]
Thanks for the additional input. It makes total sense to me. Apologies for the trouble it has brought to you. The team is actively looking into a short-term solution in the coming release to reenable your scenario in a safe manner, while we're also investigating an elegant long-term solution. Please stay tuned.

**Comment by Elad-Moshe** [comment]
I have the same issue with MS Access files. 
Tried to fix it for 3 days until I saw this post.
Definitely would want to see a proper solution from the Microsoft team.

**Comment by Elad-Moshe** [comment]
I have the same issue with MS Access files. 
Tried to fix it for 3 days until I saw this post.
Definitely would want to see a proper solution from the Microsoft team.

**Comment by KeynesY** [comment]
Thanks for the feedback. The team is working on a short-term solution with high priority. You may stay with the old version a bit. Thanks for the patience.

**Comment by Elad-Moshe** [comment]
I have already upgraded to the newer version and now working on a way to downgrade the version back.
Also, in my Data factory I have an activity to upgrade the IR to the newest version and now it will require me to rebuild my piplines.
Please work it out quickly.

**Comment by fjivanjee** [comment]
Similar Issue here too and works with 5.21. I did not see anything relating to this on the release notes and so its bit surprising if its to fix a security hole. I would support blocking the local drive, however is it not the login credentials used in the linked services that would be used for the drive location? So if the user does not have access to system files and executions it should be a best practice notice to follow on the connection rather than completely blocking it out.

**Comment by KeynesY** [comment]
Thanks fjivanjee for the feedback. Agree with your points. We will improve the notification and best practice sharing.

In majority cases, you're right. The login credential would be used to impersonate, but there might be a worry that in an edge case scenario when no login credential is passed in, hence service account would be used to access local folders. There is no proof that this is happening, but since SHIR has so many connectors / capabilities, it's a huge test matrix for which we can't possibly exhaust the tests. The best / simple way to keep SHIR safe is to avoid any local host / folder access as much as we can. Hope this explains the motivation of the change.

**Comment by KeynesY** [comment]
We released a hotfix for SHIR last week that allows SHIR admin to opt out the security control for File System. Longer term, we would provide a finer granular control over folders.
We have notified every customer whose subscription has been affected by the File System connector. You can see details in release note.
MS Access should continue to work. If not, we will do better communication than this time. Sorry for the inconvenience and thanks for your patience.

**Comment by daharmon** [comment]
I installed the new version and set the flag to opt out of the file system security control. It looks good so far in my connection tests. Our daily jobs will run tomorrow morning so we'll know for sure at that point. Thank you for providing a fix!
